#############
# BASIC
#############

### frontpage
GET http://localhost:3000

### ping
GET http://localhost:3000/api/v1/ping

### error
GET http://localhost:3000/api/v1/zzz

### exception
POST http://localhost:3000/api/v1/check_file

### favicon
GET http://localhost:3000/favicon.ico

### default config
GET http://localhost:3000/api/v1/default_config
